services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.production
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3002:3000"
    volumes:
      - ./content:/app/content
      - ./public/uploads:/app/public/uploads
    networks:
      - blog_net

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: neon_blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d neon_blog"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - blog_net


volumes:
  postgres_data:

networks:
  blog_net:
